export const GET_ITEMS='GET_ITEMS'
export const ADD_ITEM='ADD_ITEM'
export const DELETE_ITEM='DELETE_ITEM'
export const ITEMS_LOADING='ITEMS_LOADING'
export const UPDATE_ITEM='UPDATE_ITEM'


export const GET_BOOKS='GET_BOOKS'
export const ADD_BOOK='ADD_BOOK'
export const DELETE_BOOK='DELETE_BOOK'
export const BOOKS_LOADING='BOOKS_LOADING'
export const UPDATE_BOOK='UPDATE_BOOK'
export const ADD_FAILED='ADD_FAILED'
export const GET_BOOK='GET_BOOK'


export const USER_LOADING='USER_LOADING'
export const USER_LOADED='USER_LOADED'
export const AUTH_ERROR='AUTH_ERROR'
export const LOGIN_SUCCESS='LOGIN_SUCCESS'
export const LOGIN_FAIL='LOGIN_FAIL'
export const LOGOUT_SUCCESS='LOGOUT_SUCCESS'
export const REGISTER_SUCCESS='REGISTER_SUCCESS'
export const REGISTER_FAIL='REGISTER_FAIL'
export const ADMIN_LOADED='ADMIN_LOADED'
export const ADMIN_LOADING='ADMIN_LOADING'


export const BORROWER_LOADING='BORROWER_LOADING'
export const BORROWER_LOADED='BORROWER_LOADING'
export const GET_BORROWER='GET_BORROWER'


export const GET_ALL_ENQUIRIES='GET_ALL_ENQUIRIES'
export const GET_USER_ENQUIRIES='GET_USER_ENQUIRIES'
export const SUBMIT_ENQUIRY='SUBMIT_ENQUIRY'
export const UPDATE_ENQUIRY='UPDATE_ENQUIRY'
export const ENQUIRIES_LOADING='ENQUIRIES_LOADING'
export const GET_ENQUIRY='GET_ENQUIRY'



export const GET_ALL_REQUESTS='GET_ALL_REQUESTS'
export const GET_USER_REQUESTS='GET_USER_REQUESTS'
export const SUBMIT_REQUEST='SUBMIT_REQUEST'
export const UPDATE_REQUEST='UPDATE_REQUEST'



export const GET_ERRORS='GET_ERRORS'
export const CLEAR_ERRORS='CLEAR_ERRORS'




